version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.4
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  # deploy all
  deploy:
    docker:
      - image: circleci/node:8.10
      - image: circleci/python:3.4
    steps:
      - checkout
      - run: mkdir bucket && echo "lorem ipsum" > bucket/build_asset.txt
      - run:
          name: Parcel build
          command: npm run build
      - aws-s3/sync:
          from: bucket/build_asset.txt
          to: "s3://react-app-from-ekpono"
          aws-access-key-id: ${AWS_ACCESS_KEY_ID}
          aws-region: ${AWS_REGION}
          aws-secret-access-key: ${AWS_SECRET_ACCESS_KEY}
          arguments: --dryrun