version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.4
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/project
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  # deploy all
  deploy:
    docker:
      - image: circleci/node:8.10
      - image: circleci/python:3.4
    working_directory: ~/flash-web-front
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Parcel build
          command: npm run build
      - aws-s3/sync:
          from: ~/flash-web-front/dist
          to: "s3://react-app-from-ekpono/"