version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.4
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  # deploy all
  deploy:
    docker:
      - image: circleci/node:8.10
      - image: circleci/python:3.4
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Parcel build
          command: npm run build
      - aws-s3/sync:
          from: build
          to: "s3://react-app-from-ekpono/"
          aws-access-key-id: "ZDmOKPcfX6+vE7mqXwsTjGcJTGdFC6lk1sU/7lPk"
          aws-region: "us-east-2"
          aws-secret-access-key: "AKIAXXFWKQG52J3QVFNC"
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true